name: CI Dev Deployment Test
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Build Artifact
        run: zip -r build.zip src requirements.txt
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Tests
        run: |
          echo "Running Unit Tests..."
          pytest -v tests

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Simulate Dev Deployment
        run: |
          echo "Build artifact downloaded. Simulating deployment to dev environment."
          echo "Deployment successful."